## Request timeout
# timeout: 5s

## Customizable template file path
## In docker, by default the current working directory is set to /prometheus-webhook-dingtalk
## However it's recommended to use absolute path whenever possible
# template: template/default.tmpl
targets:
  webhook1:
    url: https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxxxxxx
    # secret for signature
    secret: this_is_secret
  webhook2:
    url: https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxxxxxx
