version: 2.1

orbs:
  prometheus: prometheus/prometheus@0.1.0
  go: circleci/go@0.2.0

jobs:
  test:
    # Whenever the Go version is updated here, .promu.yml should also be updated.
    docker:
      - image: circleci/golang:1.13

    steps:
      - prometheus/setup_environment
      - go/load-cache:
        key: v1-go-mod
      - run: make
      - go/save-cache:
          key: v1-go-mod
      - prometheus/store_artifact:
          file: prometheus-webhook-dingtalk
  build:
    description: >
      Cross-build and store the binaries.
    machine:
      enabled: true

    steps:
      - prometheus/setup_environment
      - run: promu crossbuild -v
      - persist_to_workspace:
          root: .
          paths:
            - .build
      - store_artifacts:
          path: .build
          destination: /build

  publish_master:
    description: >
      Build and publish container images from the master branch.
    docker:
      - image: circleci/golang
    steps:
      - prometheus/setup_build_environment
      - prometheus/publish_images:
          registry: docker.io
          organization: timonwong
          login_variable: DOCKER_LOGIN
          password_variable: DOCKER_PASSWORD
      - prometheus/publish_images:
          registry: quay.io
          organization: timonwong
          login_variable: QUAY_LOGIN
          password_variable: QUAY_PASSWORD

  publish_release:
    description: >
      Build and publish binaries and container images for a given release tag.
    parameters:
      image:
        type: string
        description: Custom container image.
        default: circleci/golang

    docker:
      - image: << parameters.image >>

    steps:
      - prometheus/setup_build_environment
      - run: promu crossbuild tarballs
      - run: promu checksum .tarballs
      - run: promu release .tarballs
      - store_artifacts:
          path: .tarballs
          destination: releases
      - prometheus/publish_release_images:
          registry: docker.io
          organization: timonwong
          login_variable: DOCKER_LOGIN
          password_variable: DOCKER_PASSWORD
      - prometheus/publish_release_images:
          registry: quay.io
          organization: timonwong
          login_variable: QUAY_LOGIN
          password_variable: QUAY_PASSWORD

workflows:
  version: 2
  prometheus-webhook-dingtalk:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          name: build
          filters:
            tags:
              only: /.*/
      - publish_master:
          context: timonwong-context
          requires:
            - test
            - build
          filters:
            branches:
              only: master
      - publish_release:
          context: timonwong-context
          requires:
            - test
            - build
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
            branches:
              ignore: /.*/
